# Generated by Django 6.0.2 on 2026-03-30 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_paciente', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Paciente')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('DNI', models.CharField(max_length=10, verbose_name='DNI')),
                ('lugar_nacimiento', models.CharField(max_length=100, verbose_name='Lugar de Nacimiento')),
                ('edad', models.IntegerField(verbose_name='Edad')),
                ('sexo', models.CharField(max_length=50, verbose_name='Sexo')),
                ('estado_civil', models.CharField(max_length=50, verbose_name='Estado Civil')),
                ('domicilio_actual', models.CharField(max_length=150, verbose_name='Domicilio Actual')),
                ('domicilio_procedencia', models.CharField(max_length=150, verbose_name='Domicilio de Procedencia')),
                ('celular', models.CharField(max_length=20, verbose_name='Celular')),
                ('ocupacion', models.CharField(max_length=100, verbose_name='Ocupación')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de Ingreso')),
                ('estado', models.CharField(max_length=50, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['nombre'],
            },
        ),
    ]
