# Generated by Django 6.0.2 on 2026-04-02 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paciente',
            options={},
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='update_at',
        ),
        migrations.AlterField(
            model_name='paciente',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='id_paciente',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True, verbose_name='ID Paciente'),
        ),
    ]
