# Generated by Django 6.0.2 on 2026-05-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_alter_paciente_options_remove_paciente_update_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='dni_acompanante',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='DNI Acompañante'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='domicilio_acompanante',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Domicilio Acompañante'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='grado_instruccion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Grado de Instrucción'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='nombre_acompanante',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre del Acompañante'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='nombre_madre',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre de la Madre'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='nombre_padre',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre del Padre'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='religion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Religión'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fecha_ingreso',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de Ingreso'),
        ),
    ]
