# Generated by Django 6.0.2 on 2026-04-17 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0002_alter_paciente_options_remove_paciente_update_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IngresoHospitalario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_historia_clinica', models.CharField(max_length=50, unique=True)),
                ('cama', models.CharField(max_length=20)),
                ('servicio', models.CharField(max_length=100)),
                ('fecha_ingreso', models.DateField()),
                ('hora_ingreso', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingresos_hospitalarios', to='pacientes.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='InformeOperatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_operacion', models.CharField(max_length=50)),
                ('diagnostico_pre_op', models.TextField()),
                ('diagnostico_post_op', models.TextField()),
                ('operacion_realizada', models.TextField()),
                ('cirujano', models.CharField(max_length=150)),
                ('anestesiologo', models.CharField(max_length=150)),
                ('tecnica_anestesica', models.CharField(max_length=150)),
                ('h_inicio_op', models.TimeField()),
                ('h_fin_op', models.TimeField()),
                ('descripcion_operacion', models.TextField()),
                ('tipo_herida', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=5)),
                ('ingreso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='historia_hp.ingresohospitalario')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriaFiliacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raza', models.CharField(blank=True, max_length=50)),
                ('religion', models.CharField(blank=True, max_length=50)),
                ('nombre_padre', models.CharField(blank=True, max_length=150)),
                ('nombre_madre', models.CharField(blank=True, max_length=150)),
                ('acompanante_nombre', models.CharField(blank=True, max_length=150)),
                ('acompanante_dni', models.CharField(blank=True, max_length=15)),
                ('acompanante_domicilio', models.CharField(blank=True, max_length=255)),
                ('enfermedad_actual', models.TextField(blank=True)),
                ('ingreso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='historia_hp.ingresohospitalario')),
            ],
        ),
        migrations.CreateModel(
            name='ExamenClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.CharField(max_length=10)),
                ('fc', models.CharField(max_length=10)),
                ('fr', models.CharField(max_length=10)),
                ('pa', models.CharField(max_length=20)),
                ('peso', models.CharField(max_length=10)),
                ('talla', models.CharField(max_length=10)),
                ('imc', models.CharField(max_length=10)),
                ('examen_general', models.TextField(help_text='Estado de conciencia, nutrición, piel, etc.')),
                ('examen_regional', models.TextField(help_text='Cabeza, Cuello, Tórax, Abdomen, etc.')),
                ('ingreso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='historia_hp.ingresohospitalario')),
            ],
        ),
        migrations.CreateModel(
            name='EvolucionMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('apreciacion_subjetiva', models.TextField()),
                ('apreciacion_objetiva', models.TextField()),
                ('tratamiento_plan_trabajo', models.TextField()),
                ('firma_medico', models.CharField(max_length=150)),
                ('ingreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evoluciones_medicas', to='historia_hp.ingresohospitalario')),
            ],
        ),
        migrations.CreateModel(
            name='EvolucionEnfermeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('anotacion', models.TextField()),
                ('ingresos_liquidos', models.CharField(blank=True, max_length=50)),
                ('egresos_liquidos', models.CharField(blank=True, max_length=50)),
                ('ingreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_enfermeria', to='historia_hp.ingresohospitalario')),
            ],
        ),
        migrations.CreateModel(
            name='ConsentimientoInformado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medico_responsable', models.CharField(max_length=150)),
                ('especialidad', models.CharField(max_length=100)),
                ('riesgos_procedimiento', models.TextField()),
                ('consecuencias_no_realizar', models.TextField()),
                ('firma_paciente_confirmada', models.BooleanField(default=False)),
                ('ingreso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='historia_hp.ingresohospitalario')),
            ],
        ),
        migrations.CreateModel(
            name='TerapiaPrescripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_prescripcion', models.DateTimeField()),
                ('terapia', models.TextField()),
                ('via_administracion', models.CharField(max_length=100)),
                ('horario', models.CharField(max_length=100)),
                ('ingreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terapias', to='historia_hp.ingresohospitalario')),
            ],
        ),
    ]
