# Generated by Django 6.0.2 on 2026-05-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia_hp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historiafiliacion',
            name='acompanante_dni',
        ),
        migrations.RemoveField(
            model_name='historiafiliacion',
            name='acompanante_domicilio',
        ),
        migrations.RemoveField(
            model_name='historiafiliacion',
            name='acompanante_nombre',
        ),
        migrations.AddField(
            model_name='historiafiliacion',
            name='documento_identidad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historiafiliacion',
            name='documento_identidad_acompanante',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historiafiliacion',
            name='domicilio_acompanante_responsable',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historiafiliacion',
            name='domicilio_actual',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historiafiliacion',
            name='domicilio_procedencia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historiafiliacion',
            name='edad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historiafiliacion',
            name='estado_civil',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historiafiliacion',
            name='fecha_entrevista',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historiafiliacion',
            name='fecha_ingreso',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historiafiliacion',
            name='grado_instruccion',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='historiafiliacion',
            name='hora_entrevista',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historiafiliacion',
            name='hora_ingreso',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historiafiliacion',
            name='informacion_confiable',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historiafiliacion',
            name='lugar_fecha_nacimiento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historiafiliacion',
            name='nombre_apellido_acompanante',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historiafiliacion',
            name='nombres_apellidos',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historiafiliacion',
            name='ocupacion',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='historiafiliacion',
            name='sexo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historiafiliacion',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historiafiliacion',
            name='enfermedad_actual',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historiafiliacion',
            name='nombre_madre',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='historiafiliacion',
            name='nombre_padre',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='historiafiliacion',
            name='raza',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historiafiliacion',
            name='religion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
