# Generated by Django 6.0.2 on 2026-03-30 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nom_usuario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
