# Generated by Django 6.0.2 on 2026-04-02 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0002_alter_paciente_options_remove_paciente_update_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_historial', models.CharField(max_length=50, verbose_name='N° de Historia Clínica')),
                ('especialidad', models.CharField(choices=[('Colposcopia', 'Colposcopia'), ('Crioterapia', 'Crioterapia'), ('Medicina Pediátrica', 'Medicina Pediátrica'), ('Consulta del Niño Sano', 'Consulta del Niño Sano'), ('Cirugía General', 'Cirugía General'), ('Neurocirugía', 'Neurocirugía'), ('Cirugía Plástica', 'Cirugía Plástica'), ('Cirugía Maxilofacial', 'Cirugía Maxilofacial'), ('Traumatología', 'Traumatología'), ('Urología', 'Urología'), ('Cirugía de cabeza y cuello', 'Cirugía de cabeza y cuello'), ('Otorrinolaringología', 'Otorrinolaringología'), ('Neurología', 'Neurología'), ('Cardiología', 'Cardiología'), ('Endocrinología', 'Endocrinología'), ('Gastroenterología', 'Gastroenterología'), ('Dermatología', 'Dermatología'), ('Medicina Física y Rehabilitación', 'Medicina Física y Rehabilitación'), ('Oncología Clínica', 'Oncología Clínica'), ('Psicología', 'Psicología')], max_length=100, verbose_name='Especialidad')),
                ('hora', models.TimeField(verbose_name='Hora')),
                ('grado_instruccion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Grado de Instrucción')),
                ('pa', models.CharField(blank=True, max_length=20, null=True, verbose_name='P/A')),
                ('pulso', models.CharField(blank=True, max_length=20, null=True, verbose_name='Pulso')),
                ('temperatura', models.CharField(blank=True, max_length=20, null=True, verbose_name='Temperatura')),
                ('f_respiratoria', models.CharField(blank=True, max_length=20, null=True, verbose_name='F/Respiratoria')),
                ('peso', models.CharField(blank=True, max_length=20, null=True, verbose_name='Peso')),
                ('talla', models.CharField(blank=True, max_length=20, null=True, verbose_name='Talla')),
                ('imc', models.CharField(blank=True, max_length=20, null=True, verbose_name='IMC')),
                ('alergias', models.CharField(blank=True, max_length=200, null=True, verbose_name='Alergias')),
                ('enfermedad_actual', models.TextField(verbose_name='Enfermedad Actual')),
                ('examen_fisico', models.TextField(verbose_name='Examen Físico')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historias_clinicas', to='pacientes.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Historia Clínica',
                'verbose_name_plural': 'Historias Clínicas',
                'ordering': ['-created_at'],
            },
        ),
    ]
