# Generated by Django 6.0.2 on 2026-04-02 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial_cl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiaclinica',
            name='enfermedad_actual',
            field=models.TextField(blank=True, null=True, verbose_name='Enfermedad Actual'),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='examen_fisico',
            field=models.TextField(blank=True, null=True, verbose_name='Examen Físico'),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='hora',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora'),
        ),
    ]
