# Generated by Django 6.0.2 on 2026-05-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial_cl', '0002_alter_historiaclinica_enfermedad_actual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiaclinica',
            name='fecha_registro',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Registro'),
        ),
    ]
