# Generated by Django 6.0.2 on 2026-05-08 13:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial_cl', '0003_historiaclinica_fecha_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiaclinica',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
