# Generated by Django 5.2.14 on 2026-05-12 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial_cl', '0004_alter_historiaclinica_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiaclinica',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
